server.port=8081
spring.application.name=sociallabs

spring.config.import=classpath:liquibase.properties,classpath:hibernate.properties


scheduling.user.agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

scheduling.cron.news.ukraine=0 0/1 * * * ?
scheduling.cron.news.lviv=0 0/1 * * * ?

scheduling.url.news.ukraine=0 0/1 * * * ?
scheduling.url.news.lviv=https://www.ukr.net/news/lviv.html

workflow.security.encryption.key=ENCRYPTION_KEY


#spring.telegram.client.api-id=${TELEGRAM_API_ID}
#spring.telegram.client.api-hash=${TELEGRAM_API_HASH}
#spring.telegram.client.phone=${TELEGRAM_API_PHONE}
#spring.telegram.client.database-encryption-key=${TELEGRAM_API_DATABASE_ENCRYPTION}
#spring.telegram.client.device-model=my_telegram
#spring.telegram.client.use-message-database=true
#spring.telegram.client.use-file-database=true
#spring.telegram.client.use-chat-info-database=true
#spring.telegram.client.use-secret-chats=true
#spring.telegram.client.log-verbosity-level=1
#spring.telegram.client.database-directory=/my/directory/database


jwt.secret=your-super-secret-jwt-key-change-this-in-production-minimum-256-bits-required
jwt.expiration=86400000