server.port=8081
spring.application.name=sociallabs

spring.config.import=classpath:liquibase.properties,classpath:hibernate.properties


scheduling.user.agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"

scheduling.cron.news.ukraine=0 0/1 * * * ?
scheduling.cron.news.lviv=0 0/1 * * * ?

scheduling.url.news.ukraine=0 0/1 * * * ?
scheduling.url.news.lviv=https://www.ukr.net/news/lviv.html

workflow.security.encryption.key=ENCRYPTION_KEY

spring.telegram.client.database-directory=/stor/data/tdlib/sessions
spring.telegram.client.download-directory=/stor/data/tdlib/downloads

jwt.secret=your-super-secret-jwt-key-change-this-in-production-minimum-256-bits-required
jwt.expiration=86400000